In [ ]:
import numpy as np
from math import pi
from numpy import sin, cos, arcsin, arccos, arctan, arctan2
from scipy.linalg import norm, det

In [ ]:
def Euler2A(fi, teta, psi):
  Rx = np.array([[1, 0, 0], [0, cos(fi), -sin(fi)], [0, sin(fi), cos(fi)]])
  Ry = np.array([[cos(teta), 0, sin(teta)], [0, 1, 0], [-sin(teta), 0, cos(teta)]])
  Rz = np.array([[cos(psi), -sin(psi), 0], [sin(psi), cos(psi), 0], [0, 0, 1]])

  return Rz @ Ry @ Rx

In [ ]:
def AxisAngle(A):
  A = np.asarray(A)
  R = A - np.identity(A.shape[0])

  p = np.cross(R[0], R[1])
  p = p / norm(p)

  u = np.array([p[1], -p[0], 0])
  up = A @ u

  fi = arccos(u @ up / (norm(u) * norm(up)))

  if det(np.array([u, up, p])) < 0:
      p = -p

  return p, fi

In [ ]:
def Rodrigez(p, fi):
  p = np.asarray(p)
  p = p / norm(p)

  p1, p2, p3 = p
  px = np.array([[0, -p3, p2], [p3, 0, -p1], [-p2, p1, 0]])

  E = np.identity(p.shape[0])
  p = np.atleast_2d(p).T

  return p @ p.T + cos(fi) * (E - p @ p.T) + sin(fi) * px

In [ ]:
def A2Euler(A):
  A = np.asarray(A)

  if A[2, 0] < 1:
      if A[2, 0] > -1:
          psi = arctan2(A[1, 0], A[0, 0])
          teta = arcsin(-A[2, 0])
          fi = arctan2(A[2, 1], A[2, 2])
      else:
          psi = arctan2(-A[0, 1], A[1, 1])
          teta = pi / 2
          fi = 0
  else:
      psi = arctan2(-A[0, 1], A[1, 1])
      teta = -pi / 2
      fi = 0

  return fi, teta, psi

In [ ]:
def AxisAngle2Q(p, fi):
  w = cos(fi / 2)
  p = np.asarray(p)
  p = p / norm(p)
  x, y, z = sin(fi / 2) * p

  return np.array([x, y, z, w])

In [ ]:
def Q2AxisAngle(q):
  q = np.asarray(q)
  q = q / norm(q)
  w = q[-1]

  if w < 0:
      q = -q

  fi = 2 * arccos(w)

  if abs(w) == 1:
      p = np.array([1, 0, 0])
  else:
      tmp = np.array([q[0], q[1], q[2]])
      p = tmp / norm(tmp)

  return p, fi

**PROFESOROVI TEST PRIMERI**

In [ ]:
A = Euler2A(-arctan(1 / 4), -arcsin(8 / 9), arctan(4))
print(A)

[[ 0.11111111 -0.88888889 -0.44444444]
 [ 0.44444444  0.44444444 -0.77777778]
 [ 0.88888889 -0.11111111  0.44444444]]


In [ ]:
p, fi = AxisAngle(A)
print(p)
print(fi)

[ 0.33333333 -0.66666667  0.66666667]
1.5707963267948968


In [ ]:
R = Rodrigez([1 / 3, -2 / 3, 2 / 3], pi / 2)
print(R)

[[ 0.11111111 -0.88888889 -0.44444444]
 [ 0.44444444  0.44444444 -0.77777778]
 [ 0.88888889 -0.11111111  0.44444444]]


In [ ]:
fi_, teta_, psi_ = A2Euler(A)
print(fi_, teta_, psi_)

-0.24497866312686414 -1.09491407713448 1.3258176636680326


In [ ]:
q = AxisAngle2Q([1 / 3, -2 / 3, 2 / 3], pi / 2)
print(q)

[ 0.23570226 -0.47140452  0.47140452  0.70710678]


In [ ]:
p, fi = Q2AxisAngle(q)
print(p)
print(fi)

[ 0.33333333 -0.66666667  0.66666667]
1.5707963267948966


**NOVI TEST PRIMERI**

In [ ]:
A = Euler2A(3 / 4, 1 / 2, 2 / 3)
print(A)

[[ 0.68968096 -0.19563025  0.69718648]
 [ 0.54267056  0.77710514 -0.31877307]
 [-0.47942554  0.59819429  0.64211739]]


In [ ]:
p, fi = AxisAngle(A)
print(p)
print(fi)

[0.55091917 0.70691515 0.4435753 ]
0.9830922966962168


In [ ]:
R = Rodrigez(p, fi)
print(R)

[[ 0.68968096 -0.19563025  0.69718648]
 [ 0.54267056  0.77710514 -0.31877307]
 [-0.47942554  0.59819429  0.64211739]]


In [ ]:
fi_, teta_, psi_ = A2Euler(A)
print(fi_, teta_, psi_)

0.7499999999999999 0.5 0.6666666666666666


In [ ]:
q = AxisAngle2Q([2 / 3, 1 / 4, 2 / 5], pi / 3)
print(q)

[0.40816327 0.15306122 0.24489796 0.8660254 ]


In [ ]:
p, fi = Q2AxisAngle(q)
print(p)
print(fi)

[0.81632653 0.30612245 0.48979592]
1.0471975511965974
